apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - deployment-frontend.yaml
  - service.yaml
  - service-frontend.yaml
  - route.yaml